expose:
  ingress:
    className: traefik
    hosts: 
      core: k8s-harbor.docker-compose.zip
  tls:
    certSource: secret
    secret:
      secretName: "k8s-harbor-docker-compose-zip-tls"
externalURL: https://k8s-harbor.docker-compose.zip
harborAdminPassword: "Harbor12345"